<a href="https://colab.research.google.com/github/stbhg5/ComputerScience/blob/main/python_ch11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. numpy에 대해

In [2]:
import numpy as np

np.array([1, 2, 3, 4]) # 이미 정의된 컬렉션을 numpy로 바꾸는 방법을 통해 많이 생성함

array([1, 2, 3, 4])

In [4]:
np.array([1, 2, 3, 4]).dtype # 64비트 인트

dtype('int64')

In [5]:
np.array(['a', 'b', 'c']).dtype # 유니코드 같은 게 나옴

dtype('<U1')

In [7]:
np.array([1.5, 1.2, 1.8]).dtype # 64비트 float

dtype('float64')

In [3]:
np.empty(10) # 배열 크기가 10인 numpy array가 생성

array([1.34033449e-316, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.01346930e-154, 1.87054506e-051, 3.88585872e-033, 5.33382628e-091,
       5.28785869e+174, 6.01347042e-154])

In [12]:
np.array([1, 2, 3, 4], dtype = np.float64).dtype # 자료형 강제 지정

dtype('float64')

In [14]:
data = np.array([1, 2, 3, 4], dtype = np.float64)
data # float 자료형

array([1., 2., 3., 4.])

In [15]:
np.array([[1, 2] ,[2, 2], [3, 2], [4, 2]]).shape # 원소가 2개짜리가 4개

(4, 2)

In [16]:
np.array([[1, 2, 3, 4], [2, 2, 3, 4]]).shape  # 원소가 4개자리가 2개
# 즉 배열에서 제일 안쪽의 원소로 갈수록 .shape로 얻어낸 값의 괄호 오른쪽으로 가고 바깥 원소일수록 괄호 왼쪽으로 간다.

(2, 4)

In [17]:
np.zeros(3, dtype = np.int64)

array([0, 0, 0])

In [21]:
np.zeros((3, 5, 1)) # 다차원 배열

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [23]:
np.eye(5) # 대각선 부분만 1 : 대각 행렬

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
a = np.empty((3, 5))

In [32]:
a[0] = 1 # 다차원 배열에서 특정 차원 숫자 바꾸면 그 원소 전부 변하는 특성!
a[1] = 2
a[2] = 3

In [33]:
a

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]])

In [34]:
a.shape

(3, 5)

In [35]:
a[[0,2]] # 0, 2행만 골라서 가져오고 싶을 때 이렇게 가져올 수 있는 특성!

array([[1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3.]])

In [51]:
a = np.empty((3, 5))
for i in range(15):
    a[i//5][i%5] = i # 5로 나눈 몫과 나머지로 대응

In [39]:
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [52]:
a[[1, 2], [0, 3]]

array([ 5., 13.])

In [55]:
a = [1, 2, 3, 4]
# b = a
b = a[0:4] # 슬라이싱은 복제된 값 가져온다.
b[1] = 4
a
# 넘파이 배열은 슬라이싱할 경우 복제되지 않는데, 그 배열의 주소만 가져오기 때문이다. 따라서 .copy()를 통해 복사해야 한다.

[1, 2, 3, 4]

In [56]:
a = np.array([1, 2, 3, 4])
a == 1 # array의 요소 하나하나 별로 비교한다.

array([ True, False, False, False])

In [60]:
(a == 1) | (a == 2)

array([ True,  True, False, False])

In [62]:
a[[1, 3]]

array([2, 4])

In [61]:
a[np.array([False, True, False, True])] # a의 크기와 동일한 bool 타입 array를 안에 집어넣을 경우, True의 해당하는 위치의 원소만 가지고 부분 array가 나온다.

array([2, 4])

In [64]:
a[(a == 2) | (a == 4)] # 조건에 해당하는 요소만 가져와 부분 array 만듦.

array([2, 4])

In [68]:
a = np.empty((3, 5))
for i in range(15):
    a[i//5][i%5] = i
a.flatten() # 다차원 배열을 1차원으로 펼침

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [70]:
a = np.empty((3, 5))
for i in range(15):
    a[i//5][i%5] = i
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [71]:
a.transpose() # 행과 열을 변환

array([[ 0.,  5., 10.],
       [ 1.,  6., 11.],
       [ 2.,  7., 12.],
       [ 3.,  8., 13.],
       [ 4.,  9., 14.]])

In [72]:
a = np.empty((3, 5))
for i in range(15):
    a[i // 5][i % 5] = i
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [73]:
a.shape

(3, 5)

In [74]:
a.reshape(5, 3) # 다차원 배열의 shape을 바꿈

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

In [75]:
a.reshape(1, 15)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14.]])

In [76]:
np.random.random() # 난수 발생

0.7766460033726635

In [77]:
np.random.random(5)

array([0.85264506, 0.1326009 , 0.3420036 , 0.5088994 , 0.21974451])

In [78]:
np.random.random((5, 3))

array([[0.42549001, 0.06379919, 0.1559296 ],
       [0.68151284, 0.60598763, 0.88769601],
       [0.43532136, 0.51213166, 0.83607711],
       [0.07349979, 0.95226116, 0.00705371],
       [0.46022681, 0.11504063, 0.10320787]])

In [82]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.hstack([a, b]) # 수평으로 합침

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [83]:
np.vstack([a, b]) # 수직으로 합침

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

- 문제 풀이

In [85]:
import numpy as np
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2],
              [3, 4]])
print(np.prod(b)) # 1*2*3*4
print(np.prod(c, axis = 0)) # [1*3, 2*4] 0은 열
print(np.prod(c, axis = 1)) # [1*2, 3*4] 1은 행
print(np.sum(b)) # 1+2+3+4
print(np.sum(b, keepdims = True)) # [1+2+3+4] # keepdims은 차원을 유지해라
print(np.sum(c, axis = 0)) # [1+3, 2+4] 0은 열
print(np.sum(c, axis = 1)) # [1+2, 3+4] 1은 행
# axis 는 열단위로 합칠지 행단위로 합칠지 정해준다.

24
[3 8]
[ 2 12]
10
[10]
[4 6]
[3 7]


In [86]:
import numpy as np
a = np.array([2, 4, 6, 8]).reshape(2, 2)
b = np.array([2, 2, 2, 2]).reshape(2, 2)
print(a)
print(b)
print(a + b) # 엘리먼트와이스 더하기, 즉 요소 값을 더한다.
print(a - b)
print(a * b)
print(a / b)
print(np.matmul(a, b)) # 매트릭스 멀티플리케이션 : 행렬과 행렬의 곱

[[2 4]
 [6 8]]
[[2 2]
 [2 2]]
[[ 4  6]
 [ 8 10]]
[[0 2]
 [4 6]]
[[ 4  8]
 [12 16]]
[[1. 2.]
 [3. 4.]]
[[12 12]
 [28 28]]


In [88]:
import numpy as np
a1 = np.arange(1, 10).reshape(3, 3)
a2 = np.arange(11, 20).reshape(3, 3)
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
print(np.matmul(a1, a2))
print(a1 ** 3) # 세제곱

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]


In [89]:
# 일반 파이썬과 numpy의 계산속도 차이
import numpy as np
import datetime
li = range(1, 1000000)

s = datetime.datetime.now()
li2 = []
for i in li:
    li2.append(i * 2)
print(datetime.datetime.now() - s)

ar = np.array(li)
s = datetime.datetime.now()
arr2 = ar * 2
s = datetime.datetime.now()
print(datetime.datetime.now() - s)

0:00:00.292198
0:00:00.000053


In [90]:
import numpy as np
# scipy : science python 과학 연산을 위한 모듈을 가진 라이브러리
# scipy.stats : 통계에 대한 모듈
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5,
               4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
# x.sort() # 원본 데이터를 작은 것부터 큰수까지 오름차순으로 변경
print(x)
print(np.percentile(x, 0))  # 최소값
print(np.percentile(x, 25)) # 25%위치값 1사분위수 1/4
print(np.percentile(x, 50)) # 중앙값    2사분위수 1/4 * 2
print(np.percentile(x, 75)) # 75%위치값 3사분위수 1/4 * 3
print(np.percentile(x, 100)) # 최대값

[ 18   5  10  23  19  -8  10   0   0   5   2  15   8   2   5   4  15  -1
   4  -7 -24   7   9  -6  23 -13]
-24.0
0.0
5.0
10.0
23.0


In [93]:
import numpy as np
a1 = np.ones((2,3))
print(a1)
a2 = np.zeros((2, 2))
print(a2)
# hstack/vstack : 두개를 붙인 새로운 배열을 생성
# hstack : horizontal stack 수평으로 붙임 
print(np.hstack([a1, a2]))
a3 = np.zeros((3,3))
# vstack vertical stack  수직으로 이어 붙임 
print(a3)
a4 = np.vstack([a1, a3])
print(a4)
print(a1)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [95]:
import numpy as np
ar1 = np.array([1, 2, 3, 4])
br1 = np.array([5, 6, 7, 8])
cr1 = np.concatenate((ar1, br1)) 
print(cr1)
ar2 = np.array([[1, 2],
                [3, 4]])
br2 = np.array([[5, 6],
                [7, 8]])
cr1 = np.concatenate((ar2, br2), axis = 0) # 0은 열, vstack
cr2 = np.concatenate((ar2, br2), axis = 1) # 1은 행, hstack
print(cr1)
print(cr2)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [96]:
# 단항함수
import numpy as np
ar = np.array([10, 1, 2, 3, 4])
br = np.array([1.23, 4.567, 2.76])
cr = np.array([-7, 0, 2])
print(np.sqrt(ar)) # 제곱근
print(np.square(ar)) # 제곱
print(np.modf(br)) # 소수부분과 정수를 분리
print(np.sign(cr)) # 음수(-1), 0, 양수(1)

[3.16227766 1.         1.41421356 1.73205081 2.        ]
[100   1   4   9  16]
(array([0.23 , 0.567, 0.76 ]), array([1., 4., 2.]))
[-1  0  1]


In [97]:
import numpy as np
#               0 1 2
#              -3-2-1
ar1 = np.array([1,2,3])
print(ar1[0], ar1[1], ar1[2])
print(ar1[-1], ar1[-2], ar1[-3])
ar2 = np.array([[1,2],[3,4]])
#         행 열
print(ar2[0][0],ar2[0][1],ar2[1][0],ar2[1][1])
#         행열
print(ar2[0,0],ar2[0,1],ar2[1,0],ar2[1,1])
print(ar2[-1][-1],ar2[-2][-2])
print(ar2[-1,-1],ar2[-2,-2])
#         0행    1행
print(ar2[0], ar2[1])

1 2 3
3 2 1
1 2 3 4
1 2 3 4
4 1
4 1
[1 2] [3 4]


In [98]:
import numpy as np
# ar : 1 ~ 20  4행 5열
ar1 = np.arange(1, 21).reshape(4, 5); print(ar1)
# 1행, 3행
ar2 = ar1[[1,3]]; print(ar2)
# 0행 3열,  1행 4열
ar3 = ar1[[0,1],[3,4]];  print(ar3)
# 0과 1행 중에서 3열과 4열
ar4 = ar1[[0,1]][:,[3,4]]; print(ar4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 6  7  8  9 10]
 [16 17 18 19 20]]
[ 4 10]
[[ 4  5]
 [ 9 10]]


In [99]:
import numpy as np
x = np.array([[2, 1, 6], [0, 7, 4],  [5, 3, 2]])
print(x)
print(np.sort(x, axis = 1))  # 좌우 오름차순
print(np.sort(x, axis = 0))  # 상하 오름차순
print(np.sort(x, axis = 0)[::-1]) # 상하 내림차순

[[2 1 6]
 [0 7 4]
 [5 3 2]]
[[1 2 6]
 [0 4 7]
 [2 3 5]]
[[0 1 2]
 [2 3 4]
 [5 7 6]]
[[5 7 6]
 [2 3 4]
 [0 1 2]]
