<a href="https://colab.research.google.com/github/stbhg5/ComputerScience/blob/main/python_ch11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. numpy에 대해

In [ ]:
import numpy as np

np.array([1, 2, 3, 4]) # 이미 정의된 컬렉션을 numpy로 바꾸는 방법을 통해 많이 생성함

array([1, 2, 3, 4])

In [ ]:
np.array([1, 2, 3, 4]).dtype # 64비트 인트

dtype('int64')

In [ ]:
np.array(['a', 'b', 'c']).dtype # 유니코드 같은 게 나옴

dtype('<U1')

In [ ]:
np.array([1.5, 1.2, 1.8]).dtype # 64비트 float

dtype('float64')

In [ ]:
np.empty(10) # 배열 크기가 10인 numpy array가 생성

array([1.34033449e-316, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.01346930e-154, 1.87054506e-051, 3.88585872e-033, 5.33382628e-091,
       5.28785869e+174, 6.01347042e-154])

In [ ]:
np.array([1, 2, 3, 4], dtype = np.float64).dtype # 자료형 강제 지정

dtype('float64')

In [ ]:
data = np.array([1, 2, 3, 4], dtype = np.float64)
data # float 자료형

array([1., 2., 3., 4.])

In [ ]:
np.array([[1, 2] ,[2, 2], [3, 2], [4, 2]]).shape # 원소가 2개짜리가 4개

(4, 2)

In [ ]:
np.array([[1, 2, 3, 4], [2, 2, 3, 4]]).shape  # 원소가 4개자리가 2개
# 즉 배열에서 제일 안쪽의 원소로 갈수록 .shape로 얻어낸 값의 괄호 오른쪽으로 가고 바깥 원소일수록 괄호 왼쪽으로 간다.

(2, 4)

In [ ]:
np.zeros(3, dtype = np.int64)

array([0, 0, 0])

In [ ]:
np.zeros((3, 5, 1)) # 다차원 배열

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [ ]:
np.eye(5) # 대각선 부분만 1 : 대각 행렬

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a = np.empty((3, 5))

In [ ]:
a[0] = 1 # 다차원 배열에서 특정 차원 숫자 바꾸면 그 원소 전부 변하는 특성!
a[1] = 2
a[2] = 3

In [ ]:
a

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]])

In [ ]:
a.shape

(3, 5)

In [ ]:
a[[0,2]] # 0, 2행만 골라서 가져오고 싶을 때 이렇게 가져올 수 있는 특성!

array([[1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3.]])

In [ ]:
a = np.empty((3, 5))
for i in range(15):
    a[i//5][i%5] = i # 5로 나눈 몫과 나머지로 대응

In [ ]:
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [ ]:
a[[1, 2], [0, 3]]

array([ 5., 13.])

In [ ]:
a = [1, 2, 3, 4]
# b = a
b = a[0:4] # 슬라이싱은 복제된 값 가져온다.
b[1] = 4
a
# 넘파이 배열은 슬라이싱할 경우 복제되지 않는데, 그 배열의 주소만 가져오기 때문이다. 따라서 .copy()를 통해 복사해야 한다.

[1, 2, 3, 4]

In [ ]:
a = np.array([1, 2, 3, 4])
a == 1 # array의 요소 하나하나 별로 비교한다.

array([ True, False, False, False])

In [ ]:
(a == 1) | (a == 2)

array([ True,  True, False, False])

In [ ]:
a[[1, 3]]

array([2, 4])

In [ ]:
a[np.array([False, True, False, True])] # a의 크기와 동일한 bool 타입 array를 안에 집어넣을 경우, True의 해당하는 위치의 원소만 가지고 부분 array가 나온다.

array([2, 4])

In [ ]:
a[(a == 2) | (a == 4)] # 조건에 해당하는 요소만 가져와 부분 array 만듦.

array([2, 4])

In [ ]:
a = np.empty((3, 5))
for i in range(15):
    a[i//5][i%5] = i
a.flatten() # 다차원 배열을 1차원으로 펼침

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [ ]:
a = np.empty((3, 5))
for i in range(15):
    a[i//5][i%5] = i
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [ ]:
a.transpose() # 행과 열을 변환

array([[ 0.,  5., 10.],
       [ 1.,  6., 11.],
       [ 2.,  7., 12.],
       [ 3.,  8., 13.],
       [ 4.,  9., 14.]])

In [ ]:
a = np.empty((3, 5))
for i in range(15):
    a[i // 5][i % 5] = i
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [ ]:
a.shape

(3, 5)

In [ ]:
a.reshape(5, 3) # 다차원 배열의 shape을 바꿈

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

In [ ]:
a.reshape(1, 15)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14.]])

In [ ]:
np.random.random() # 난수 발생

0.7766460033726635

In [ ]:
np.random.random(5)

array([0.85264506, 0.1326009 , 0.3420036 , 0.5088994 , 0.21974451])

In [ ]:
np.random.random((5, 3))

array([[0.42549001, 0.06379919, 0.1559296 ],
       [0.68151284, 0.60598763, 0.88769601],
       [0.43532136, 0.51213166, 0.83607711],
       [0.07349979, 0.95226116, 0.00705371],
       [0.46022681, 0.11504063, 0.10320787]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.hstack([a, b]) # 수평으로 합침

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.vstack([a, b]) # 수직으로 합침

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

- 문제 풀이

In [ ]:
import numpy as np
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2],
              [3, 4]])
print(np.prod(b)) # 1*2*3*4
print(np.prod(c, axis = 0)) # [1*3, 2*4] 0은 열
print(np.prod(c, axis = 1)) # [1*2, 3*4] 1은 행
print(np.sum(b)) # 1+2+3+4
print(np.sum(b, keepdims = True)) # [1+2+3+4] # keepdims은 차원을 유지해라
print(np.sum(c, axis = 0)) # [1+3, 2+4] 0은 열
print(np.sum(c, axis = 1)) # [1+2, 3+4] 1은 행
# axis 는 열단위로 합칠지 행단위로 합칠지 정해준다.

24
[3 8]
[ 2 12]
10
[10]
[4 6]
[3 7]


In [ ]:
import numpy as np
a = np.array([2, 4, 6, 8]).reshape(2, 2)
b = np.array([2, 2, 2, 2]).reshape(2, 2)
print(a)
print(b)
print(a + b) # 엘리먼트와이스 더하기, 즉 요소 값을 더한다.
print(a - b)
print(a * b)
print(a / b)
print(np.matmul(a, b)) # 매트릭스 멀티플리케이션 : 행렬과 행렬의 곱

[[2 4]
 [6 8]]
[[2 2]
 [2 2]]
[[ 4  6]
 [ 8 10]]
[[0 2]
 [4 6]]
[[ 4  8]
 [12 16]]
[[1. 2.]
 [3. 4.]]
[[12 12]
 [28 28]]


In [ ]:
import numpy as np
a1 = np.arange(1, 10).reshape(3, 3)
a2 = np.arange(11, 20).reshape(3, 3)
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
print(np.matmul(a1, a2))
print(a1 ** 3) # 세제곱

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]


In [ ]:
# 일반 파이썬과 numpy의 계산속도 차이
import numpy as np
import datetime
li = range(1, 1000000)

s = datetime.datetime.now()
li2 = []
for i in li:
    li2.append(i * 2)
print(datetime.datetime.now() - s)

ar = np.array(li)
s = datetime.datetime.now()
arr2 = ar * 2
s = datetime.datetime.now()
print(datetime.datetime.now() - s)

0:00:00.292198
0:00:00.000053


In [ ]:
import numpy as np
# scipy : science python 과학 연산을 위한 모듈을 가진 라이브러리
# scipy.stats : 통계에 대한 모듈
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5,
               4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
# x.sort() # 원본 데이터를 작은 것부터 큰수까지 오름차순으로 변경
print(x)
print(np.percentile(x, 0))  # 최소값
print(np.percentile(x, 25)) # 25%위치값 1사분위수 1/4
print(np.percentile(x, 50)) # 중앙값    2사분위수 1/4 * 2
print(np.percentile(x, 75)) # 75%위치값 3사분위수 1/4 * 3
print(np.percentile(x, 100)) # 최대값

[ 18   5  10  23  19  -8  10   0   0   5   2  15   8   2   5   4  15  -1
   4  -7 -24   7   9  -6  23 -13]
-24.0
0.0
5.0
10.0
23.0


In [ ]:
import numpy as np
a1 = np.ones((2,3))
print(a1)
a2 = np.zeros((2, 2))
print(a2)
# hstack/vstack : 두개를 붙인 새로운 배열을 생성
# hstack : horizontal stack 수평으로 붙임 
print(np.hstack([a1, a2]))
a3 = np.zeros((3,3))
# vstack vertical stack  수직으로 이어 붙임 
print(a3)
a4 = np.vstack([a1, a3])
print(a4)
print(a1)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
ar1 = np.array([1, 2, 3, 4])
br1 = np.array([5, 6, 7, 8])
cr1 = np.concatenate((ar1, br1)) 
print(cr1)
ar2 = np.array([[1, 2],
                [3, 4]])
br2 = np.array([[5, 6],
                [7, 8]])
cr1 = np.concatenate((ar2, br2), axis = 0) # 0은 열, vstack
cr2 = np.concatenate((ar2, br2), axis = 1) # 1은 행, hstack
print(cr1)
print(cr2)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# 단항함수
import numpy as np
ar = np.array([10, 1, 2, 3, 4])
br = np.array([1.23, 4.567, 2.76])
cr = np.array([-7, 0, 2])
print(np.sqrt(ar)) # 제곱근
print(np.square(ar)) # 제곱
print(np.modf(br)) # 소수부분과 정수를 분리
print(np.sign(cr)) # 음수(-1), 0, 양수(1)

[3.16227766 1.         1.41421356 1.73205081 2.        ]
[100   1   4   9  16]
(array([0.23 , 0.567, 0.76 ]), array([1., 4., 2.]))
[-1  0  1]


In [ ]:
import numpy as np
#               0 1 2
#              -3-2-1
ar1 = np.array([1,2,3])
print(ar1[0], ar1[1], ar1[2])
print(ar1[-1], ar1[-2], ar1[-3])
ar2 = np.array([[1,2],[3,4]])
#         행 열
print(ar2[0][0],ar2[0][1],ar2[1][0],ar2[1][1])
#         행열
print(ar2[0,0],ar2[0,1],ar2[1,0],ar2[1,1])
print(ar2[-1][-1],ar2[-2][-2])
print(ar2[-1,-1],ar2[-2,-2])
#         0행    1행
print(ar2[0], ar2[1])

1 2 3
3 2 1
1 2 3 4
1 2 3 4
4 1
4 1
[1 2] [3 4]


In [ ]:
import numpy as np
# ar : 1 ~ 20  4행 5열
ar1 = np.arange(1, 21).reshape(4, 5); print(ar1)
# 1행, 3행
ar2 = ar1[[1,3]]; print(ar2)
# 0행 3열,  1행 4열
ar3 = ar1[[0,1],[3,4]];  print(ar3)
# 0과 1행 중에서 3열과 4열
ar4 = ar1[[0,1]][:,[3,4]]; print(ar4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 6  7  8  9 10]
 [16 17 18 19 20]]
[ 4 10]
[[ 4  5]
 [ 9 10]]


In [ ]:
import numpy as np
x = np.array([[2, 1, 6], [0, 7, 4],  [5, 3, 2]])
print(x)
print(np.sort(x, axis = 1)) # 좌우 오름차순
print(np.sort(x, axis = 0)) # 상하 오름차순
print(np.sort(x, axis = 0)[::-1]) # 상하 내림차순

[[2 1 6]
 [0 7 4]
 [5 3 2]]
[[1 2 6]
 [0 4 7]
 [2 3 5]]
[[0 1 2]
 [2 3 4]
 [5 7 6]]
[[5 7 6]
 [2 3 4]
 [0 1 2]]


2. pandas에 대해

In [2]:
import pandas as pd
# 리스트 형식으로 생성
pd.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], columns = ['col1', 'col2', 'col3', 'col4'])

col1  col2  col3  col4
0     1     2     3     4
1     5     6     7     8

In [3]:
# dictionary 형식으로 생성
pd.DataFrame({'col1': [1, 2, 3, 4], 'col2': [5, 6, 7, 8]})

col1  col2
0     1     5
1     2     6
2     3     7
3     4     8

In [4]:
# numpy array 형식으로 데이터 가져오기
pd.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], columns = ['col1', 'col2', 'col3', 'col4']).values

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
# column 이름 가져오기
pd.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], columns = ['col1', 'col2', 'col3', 'col4']).columns

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [8]:
# index 설정(잘 하진 않음)
pd.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], columns = ['col1', 'col2', 'col3', 'col4'], index = ['a', 'b'])

col1  col2  col3  col4
a     1     2     3     4
b     5     6     7     8

In [9]:
# row 이름 가져오기
pd.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], columns = ['col1', 'col2', 'col3', 'col4'], index = ['a', 'b']).index

Index(['a', 'b'], dtype='object')

In [12]:
# 해당 컬럼에 접근
a = pd.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], columns = ['col1', 'col2', 'col3', 'col4'])
# a['col1']
a.col1

0    1
1    5
Name: col1, dtype: int64

In [14]:
# 여러 개의 컬럼에 접근
a[['col1', 'col3']]

col1  col3
0     1     3
1     5     7

In [16]:
# 해당 행에 접근 (인덱싱은 안되고 슬라이싱을 통해 접근 가능) - 2차원 배열(DataFrame)
a[0:1]

col1  col2  col3  col4
0     1     2     3     4

In [20]:
# 특정 행하나에 접근 - 1차원 배열
a.iloc[0]

col1    1
col2    2
col3    3
col4    4
Name: 0, dtype: int64

In [22]:
# 2차원 배열로도 가져올 수 있다.
a.iloc[0:2]

col1  col2  col3  col4
0     1     2     3     4
1     5     6     7     8

In [24]:
# DataFrame에 컬럼 추가
a['col5'] = [5, 9]
a

col1  col2  col3  col4  col5
0     1     2     3     4     5
1     5     6     7     8     9

In [25]:
# DataFrame에 컬럼 값 수정
a['col5'] = a['col5'] * 10
a

col1  col2  col3  col4  col5
0     1     2     3     4    50
1     5     6     7     8    90

In [26]:
# DataFrame에 컬럼 삭제
del a['col5']
a

col1  col2  col3  col4
0     1     2     3     4
1     5     6     7     8

In [27]:
# axis가 0 또는 생략일 경우 컬럼 단위, axis가 1일 경우 row 단위로 함수 실행
a.apply(sum)

col1     6
col2     8
col3    10
col4    12
dtype: int64

In [28]:
a.apply(sum, axis = 1)

0    10
1    26
dtype: int64

In [32]:
# lambda 함수 가능
a.apply(lambda x : x[0] * x[1], axis = 0)

col1     5
col2    12
col3    21
col4    32
dtype: int64

In [35]:
# 똑같다
# a.apply(lambda x : x ** 3) # 이렇게 행열이 관련 없을경우 알아서 엘리먼트 와이즈하게(요소별로) 계산됨
a.applymap(lambda x : x ** 3)

col1  col2  col3  col4
0     1     8    27    64
1   125   216   343   512

In [42]:
a = pd.DataFrame([['2', None, 3, None], [None, 6, 7, 8]], columns = ['col1', 'col2', 'col3', 'col4'])
a
# pandas는 numpy 기반이기 때문에 None를 넣었지만 NaN이 나온다.
# '2'로 바꾸니 col1 에서 0은 2지만 1은 None다. pandas DataFrame은 컬럼별로 데이터형식이 같아야 한다. 만약 기존과 다른 형식으로 지정하면 빈 메모리인 None으로 된다.

col1  col2  col3  col4
0     2   NaN     3   NaN
1  None   6.0     7   8.0

In [43]:
# isnull() NaN이나 None인 경우 True, 그 외 False
# None : 메모리에서 아무것도 차지하지 않음
# NaN : 메모리는 차지하나 값이 숫자가 아닌 이상한 값 (Not a Number)
pd.isnull(a)

col1   col2   col3   col4
0  False   True  False   True
1   True  False  False  False

In [41]:
# dropna() : NaN이나 None 소유한 행 제외 (메서드로만 활용)
a.dropna()

Empty DataFrame
Columns: [col1, col2, col3, col4]
Index: []

In [46]:
# fillna() : Nan이나 None에 특정 수로 채움
a.fillna(3)
# 컬럼별로 데이터 타입 같아야 한다.
# NaN은 정수에 없기 때문에 실수로 표현

col1  col2  col3  col4
0    2   3.0     3   3.0
1    3   6.0     7   8.0

In [49]:
# DataFrame 작업시 그룹별로 통계분석 할 때 groupby()
a = pd.DataFrame([['기린반', 30], ['기린반', 50], ['사슴반', 40], ['사슴반', 80]], columns = ['반', '점수'])
a

반  점수
0  기린반  30
1  기린반  50
2  사슴반  40
3  사슴반  80

In [51]:
# 반별 평균
a.groupby('반').mean()

점수
반        
기린반  40.0
사슴반  60.0

In [52]:
a.groupby('반').sum()

점수
반       
기린반   80
사슴반  120

In [54]:
# 컬럼 이름 같은 것들끼리 함수 적용
a.groupby('반').agg(lambda x: sum(x) ** 2)

점수
반         
기린반   6400
사슴반  14400

In [77]:
# agg()에 함수 여러개 설정 가능
a.groupby('반').agg([lambda x: sum(x) ** 2, lambda x: sum(x)])

점수           
    <lambda_0> <lambda_1>
반                        
기린반       6400         80
사슴반      14400        120

In [57]:
import pandas as pd
items = {'apple': {'count': None,'price': None},
         'banana': {'count': None, 'price': 15000},
         'melon': {'count': 7, 'price': 1000},
         'kiwi': {'count': 20, 'price': 500},
         'mango': {'count': 30, 'price': 1500},
         'orange': {'count': 4, 'price': 700}}
data = pd.DataFrame(items)
print(data)
print('=======================')
data = pd.DataFrame(items).T # DataFrame에서의 Transpose
print(data)
print(data.fillna(0)) # NA 0으로
print(data.dropna()) # NA를 drop

      apple   banana  melon  kiwi  mango  orange
count  None      NaN      7    20     30       4
price  None  15000.0   1000   500   1500     700
       count    price
apple   None     None
banana   NaN  15000.0
melon      7     1000
kiwi      20      500
mango     30     1500
orange     4      700
        count    price
apple       0      0.0
banana      0  15000.0
melon       7   1000.0
kiwi       20    500.0
mango      30   1500.0
orange      4    700.0
       count price
melon      7  1000
kiwi      20   500
mango     30  1500
orange     4   700


In [59]:
import pandas as pd
import numpy as np
fr = pd.DataFrame(np.arange(8).reshape(2, 4), columns=['d', 'a', 'b', 'c'])
print(fr)
print('\n')
print(fr.sort_values(by = 'b')) # b값이 오름차순
print('\n')
print(fr.sort_values(ascending = False, by = 'b')) # b값이 내림차순
# b값 기준으로 다른 부분도 적용된다.

   d  a  b  c
0  0  1  2  3
1  4  5  6  7


   d  a  b  c
0  0  1  2  3
1  4  5  6  7


   d  a  b  c
1  4  5  6  7
0  0  1  2  3


In [62]:
import pandas as pd
# def f1(x):
#     return x.sum()
f1 = lambda x: x.sum()
items = {'apple': {'count': 10, 'price': 1500},
         'banana': {'count': 5, 'price': 15000},
         'melon': {'count': 7, 'price': 1000},
         'kiwi': {'count': 20, 'price': 500},
         'mango': {'count': 30, 'price': 1500},
         'orange': {'count': 4, 'price': 700}}
data1 = pd.DataFrame(items).T # T는 transpose() 행열 변경
print(data1)
print('===================')
print(data1.apply(f1)) # 열별 합계
print('===================')
print(data1.apply(f1, axis = 1)) # 행별로 합계

        count  price
apple      10   1500
banana      5  15000
melon       7   1000
kiwi       20    500
mango      30   1500
orange      4    700
count       76
price    20200
dtype: int64
apple      1510
banana    15005
melon      1007
kiwi        520
mango      1530
orange      704
dtype: int64


In [66]:
import pandas as pd
items = {'apple': {'count': 10, 'price': 1500},
         'banana': {'count': 5, 'price': 15000},
         'melon': {'count': 7, 'price': 1000},
         'kiwi': {'count': 20, 'price': 500},
         'mango': {'count': 30, 'price': 1500},
         'orange': {'count': 4, 'price': 700}}
data1 = pd.DataFrame(items).transpose() # 행열 변경
print(data1)
print('===================')
print(data1.applymap(lambda x: x * 2))  # 건건이 적용

        count  price
apple      10   1500
banana      5  15000
melon       7   1000
kiwi       20    500
mango      30   1500
orange      4    700
        count  price
apple      20   3000
banana     10  30000
melon      14   2000
kiwi       40   1000
mango      60   3000
orange      8   1400


In [68]:
import pandas as pd
# dictionary
data = {"2015": [990432, 3448737, 2890451, 2466052],
        "2010": [9631482, 3393191, 2632035, 2431774],
        "2005": [9762546, 3512547, 2517680, 2456016],
        "2000": [9853972, 3655437, 2466338, 2473990],
        "지역": ["수도권", "경상권", "수도권", "경상권"],
        "2010-2015증가율":[0.0283, 0.0163, 0.0982, 0.0141]
        }
column=["지역", "2015", "2010", "2005", "2000", "2010-2015증가율"]
df = pd.DataFrame(data, columns = column)
print(df['지역'])
print('===================')
print(df[['2010','2015']])
print('===================')
print(df['2010']) # 컬럼명 x
print('===================')
print(df[['2010']]) # 컬럼명 포함
print('===================')
print(type(df['2010'])) # 컬럼명 x, df -> Series
print('===================')
print(type(df[['2010']])) # 컬럼명 포함 -> dataframe유지

0    수도권
1    경상권
2    수도권
3    경상권
Name: 지역, dtype: object
      2010     2015
0  9631482   990432
1  3393191  3448737
2  2632035  2890451
3  2431774  2466052
0    9631482
1    3393191
2    2632035
3    2431774
Name: 2010, dtype: int64
      2010
0  9631482
1  3393191
2  2632035
3  2431774
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


In [74]:
# pandas DataFrame를 하드에 저장시 .csv 파일로 저장한다. (엑셀 비슷함)
a.to_csv('test.csv', index = False)
# a.to_csv('/content/sample_data/test.csv') # 경로 설정하여 저장

In [71]:
a

반  점수
0  기린반  30
1  기린반  50
2  사슴반  40
3  사슴반  80

In [75]:
# .csv 파일 읽기
pd.read_csv('test.csv')

반  점수
0  기린반  30
1  기린반  50
2  사슴반  40
3  사슴반  80